-- Runtime hardening synced from production Supabase on 2026-09-18.
-- Apply after supabase/schema.sql on a fresh environment.

create schema if not exists private;

create or replace function private.protect_profile_entitlements()
returns trigger language plpgsql security definer set search_path to 'pg_catalog','public'
as $$
declare v_uid uuid:=auth.uid(); v_is_admin boolean:=false; v_trial_days integer:=30; v_has_profile boolean:=false;
begin
 if v_uid is null then return new; end if;
 select exists(select 1 from public.admin_users a where a.user_id=v_uid) into v_is_admin;
 if v_is_admin then return new; end if;
 if tg_op='INSERT' then
   select coalesce(trial_days,30) into v_trial_days from public.business_settings where id='main';
   select exists(select 1 from public.profiles p where p.user_id=v_uid or p.created_by=v_uid) into v_has_profile;
   new.user_id:=v_uid; new.created_by:=v_uid; new.status:='trial'; new.current_period_end:=null;
   new.trial_ends_at:=case when v_has_profile then now() else now()+make_interval(days=>greatest(0,least(v_trial_days,365))) end;
   return new;
 end if;
 if new.user_id is distinct from old.user_id or new.created_by is distinct from old.created_by or new.status is distinct from old.status or new.trial_ends_at is distinct from old.trial_ends_at or new.current_period_end is distinct from old.current_period_end then
  raise exception 'No puedes modificar propiedad, plan o vigencia de la tarjeta.' using errcode='42501';
 end if;
 return new;
end; $$;
revoke all on function private.protect_profile_entitlements() from public,anon,authenticated;

drop trigger if exists protect_profile_entitlements on public.profiles;
create trigger protect_profile_entitlements before insert or update on public.profiles for each row execute function private.protect_profile_entitlements();

drop policy if exists "Public reads available profiles" on public.profiles;
create policy "Public reads available profiles" on public.profiles for select to anon using (
 (status='active' and (current_period_end is null or current_period_end>now())) or
 (status='trial' and trial_ends_at is not null and trial_ends_at>now())
);

drop policy if exists "Owners and admins read profiles" on public.profiles;
create policy "Owners and admins read profiles" on public.profiles for select to authenticated using (
 user_id=(select auth.uid()) or created_by=(select auth.uid()) or
 exists(select 1 from public.admin_users a where a.user_id=(select auth.uid())) or
 (status='active' and (current_period_end is null or current_period_end>now())) or
 (status='trial' and trial_ends_at is not null and trial_ends_at>now())
);

create table if not exists public.admin_audit_log (
 id bigint generated by default as identity primary key, admin_user_id uuid references auth.users(id) on delete set null,
 action text not null, entity_type text not null, entity_id text, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists admin_audit_log_created_at_idx on public.admin_audit_log(created_at desc);
create index if not exists admin_audit_log_admin_user_id_idx on public.admin_audit_log(admin_user_id);
alter table public.admin_audit_log enable row level security;

create table if not exists public.business_events (
 id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete set null,
 profile_id bigint references public.profiles(id) on delete set null, event_type text not null,
 metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create index if not exists business_events_created_at_idx on public.business_events(created_at desc);
create index if not exists business_events_user_id_idx on public.business_events(user_id);
create index if not exists business_events_profile_id_idx on public.business_events(profile_id);
alter table public.business_events enable row level security;

drop policy if exists "Users read own payments" on public.payments;
drop policy if exists "Admins read all payments" on public.payments;
drop policy if exists "Authenticated read permitted payments" on public.payments;
create policy "Authenticated read permitted payments" on public.payments for select to authenticated using (
 user_id=(select auth.uid()) or exists(select 1 from public.admin_users a where a.user_id=(select auth.uid()))
);

create or replace function private.apply_verified_payment(p_payment_id uuid,p_provider_payment_id text,p_status text,p_provider_payload jsonb)
returns table(status text,current_period_end timestamptz,activation_applied boolean)
language plpgsql security definer set search_path=''
as $$
declare v_payment public.payments%rowtype; v_profile public.profiles%rowtype; v_new_end timestamptz; v_claimed boolean:=false;
begin
 if p_status not in ('pending','approved','rejected','cancelled','refunded') then raise exception 'invalid payment status'; end if;
 select * into v_payment from public.payments where id=p_payment_id for update;
 if not found then raise exception 'payment not found'; end if;
 if v_payment.status='approved' then
   select * into v_profile from public.profiles where id=v_payment.profile_id and user_id=v_payment.user_id;
   return query select v_payment.status,v_profile.current_period_end,false; return;
 end if;
 update public.payments set provider_payment_id=p_provider_payment_id,status=p_status,provider_payload=coalesce(p_provider_payload,'{}'::jsonb),updated_at=now() where id=v_payment.id;
 if p_status='approved' then
   select * into v_profile from public.profiles where id=v_payment.profile_id and user_id=v_payment.user_id for update;
   if not found then raise exception 'profile not found'; end if;
   v_new_end=(case when v_profile.current_period_end is not null and v_profile.current_period_end>now() then v_profile.current_period_end else now() end)+interval '1 year';
   update public.profiles set status='active',current_period_end=v_new_end,updated_at=now() where id=v_profile.id;
   v_claimed:=true;
   insert into public.business_events(user_id,profile_id,event_type,metadata) values(v_payment.user_id,v_payment.profile_id,'payment_approved',jsonb_build_object('payment_id',v_payment.id,'provider_payment_id',p_provider_payment_id,'environment',v_payment.environment));
 elsif p_status='rejected' then
   insert into public.business_events(user_id,profile_id,event_type,metadata) values(v_payment.user_id,v_payment.profile_id,'payment_rejected',jsonb_build_object('payment_id',v_payment.id,'provider_payment_id',p_provider_payment_id,'environment',v_payment.environment));
 end if;
 return query select p_status,case when p_status='approved' then v_new_end else v_profile.current_period_end end,v_claimed;
end; $$;
revoke all on function private.apply_verified_payment(uuid,text,text,jsonb) from public,anon,authenticated;
grant usage on schema private to service_role;
grant execute on function private.apply_verified_payment(uuid,text,text,jsonb) to service_role;

create or replace function public.apply_verified_payment_gateway(p_payment_id uuid,p_provider_payment_id text,p_status text,p_provider_payload jsonb)
returns table(status text,current_period_end timestamptz,activation_applied boolean)
language sql security invoker set search_path='' as $$
 select * from private.apply_verified_payment(p_payment_id,p_provider_payment_id,p_status,p_provider_payload);
$$;
revoke all on function public.apply_verified_payment_gateway(uuid,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.apply_verified_payment_gateway(uuid,text,text,jsonb) to service_role;
