-- ClickOnMe MVP: esquema reproducible y políticas de acceso.
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,38}[a-z0-9]$'),
  name text not null,
  role text,
  description text,
  photo_url text,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_user_id_idx on public.profiles(user_id);
alter table public.profiles enable row level security;

drop policy if exists "Profiles are publicly readable" on public.profiles;
drop policy if exists "Users create own profile" on public.profiles;
drop policy if exists "Users update own profile" on public.profiles;
drop policy if exists "Users delete own profile" on public.profiles;

create policy "Profiles are publicly readable"
on public.profiles for select
to anon, authenticated
using (true);

create policy "Users create own profile"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users update own profile"
on public.profiles for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users delete own profile"
on public.profiles for delete
to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.profiles from anon;
grant select on table public.profiles to anon;
revoke all on table public.profiles from authenticated;
grant select, insert, update, delete on table public.profiles to authenticated;
grant usage, select on sequence public.profiles_id_seq to authenticated;

-- Controles comerciales y acceso de propietario.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;
revoke all on table public.admin_users from anon, authenticated;
grant select on table public.admin_users to authenticated;

create policy "Admins can verify their role"
on public.admin_users for select to authenticated
using (user_id = (select auth.uid()));

alter table public.profiles
  add column if not exists status text not null default 'trial'
    check (status in ('trial','active','suspended','expired')),
  add column if not exists trial_ends_at timestamptz default (now() + interval '30 days'),
  add column if not exists current_period_end timestamptz,
  add column if not exists created_by uuid references auth.users(id) on delete set null;

create table if not exists public.business_settings (
  id text primary key check (id = 'main'),
  annual_price_mxn integer not null check (annual_price_mxn > 0),
  launch_price_mxn integer check (launch_price_mxn is null or launch_price_mxn > 0),
  design_service_price_mxn integer not null check (design_service_price_mxn > 0),
  launch_promo_active boolean not null default false,
  launch_promo_label text,
  trial_days integer not null default 30 check (trial_days between 0 and 365),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);
alter table public.business_settings enable row level security;

insert into public.business_settings
  (id, annual_price_mxn, launch_price_mxn, design_service_price_mxn,
   launch_promo_active, launch_promo_label, trial_days)
values ('main', 599, 399, 1199, true, 'Promoción de inauguración', 30)
on conflict (id) do nothing;

create policy "Business settings are public"
on public.business_settings for select to anon, authenticated using (true);

create policy "Admins update business settings"
on public.business_settings for update to authenticated
using (exists (
  select 1 from public.admin_users a
  where a.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.admin_users a
  where a.user_id = (select auth.uid())
));

create policy "Admins read all profiles"
on public.profiles for select to authenticated
using (exists (
  select 1 from public.admin_users a
  where a.user_id = (select auth.uid())
));

create policy "Admins create profiles"
on public.profiles for insert to authenticated
with check (exists (
  select 1 from public.admin_users a
  where a.user_id = (select auth.uid())
));

create policy "Admins update profiles"
on public.profiles for update to authenticated
using (exists (
  select 1 from public.admin_users a
  where a.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.admin_users a
  where a.user_id = (select auth.uid())
));

create policy "Admins delete profiles"
on public.profiles for delete to authenticated
using (exists (
  select 1 from public.admin_users a
  where a.user_id = (select auth.uid())
));

revoke all on table public.business_settings from anon, authenticated;
grant select on table public.business_settings to anon, authenticated;
grant update on table public.business_settings to authenticated;

-- Archivos públicos de las tarjetas. Cada usuario solo administra su carpeta.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-assets',
  'profile-assets',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users upload own profile assets" on storage.objects;
drop policy if exists "Users read own profile assets" on storage.objects;
drop policy if exists "Users update own profile assets" on storage.objects;
drop policy if exists "Users delete own profile assets" on storage.objects;

create policy "Users upload own profile assets"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'profile-assets'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "Users read own profile assets"
on storage.objects for select to authenticated
using (
  bucket_id = 'profile-assets'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "Users update own profile assets"
on storage.objects for update to authenticated
using (
  bucket_id = 'profile-assets'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'profile-assets'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "Users delete own profile assets"
on storage.objects for delete to authenticated
using (
  bucket_id = 'profile-assets'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

-- Órdenes creadas por la integración segura de Mercado Pago.
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  provider text not null default 'mercado_pago',
  provider_order_id text unique,
  external_reference text not null unique,
  amount_mxn integer not null check (amount_mxn > 0),
  status text not null default 'created'
    check (status in ('created','pending','approved','rejected','cancelled','refunded')),
  environment text not null default 'test'
    check (environment in ('test','production')),
  checkout_url text,
  provider_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists payments_user_id_idx on public.payments(user_id);
create index if not exists payments_profile_id_idx on public.payments(profile_id);
alter table public.payments enable row level security;
drop policy if exists "Users read own payments" on public.payments;
create policy "Users read own payments"
on public.payments for select to authenticated
using ((select auth.uid()) = user_id);
revoke all on table public.payments from anon, authenticated;
grant select on table public.payments to authenticated;
