import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const origins=new Set(["https://clickonme.pro","https://www.clickonme.pro"]);
const cors=(req:Request)=>({"Access-Control-Allow-Origin":origins.has(req.headers.get("origin")??"")?req.headers.get("origin")!:"https://clickonme.pro","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"});
const json=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json"}});
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)}); if(req.method!=="POST")return json(req,{error:"Método no permitido"},405);
 try{
 const supabaseUrl=Deno.env.get("SUPABASE_URL")??"",anonKey=Deno.env.get("SUPABASE_ANON_KEY")??"",serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",mpToken=Deno.env.get("MERCADO_PAGO_ACCESS_TOKEN")??"",environment=Deno.env.get("MERCADO_PAGO_ENVIRONMENT")==="production"?"production":"test";
 if(!supabaseUrl||!anonKey||!serviceKey||!mpToken)return json(req,{error:"Configuración de pagos incompleta"},503);
 const auth=req.headers.get("Authorization")??"";const ur=await fetch(`${supabaseUrl}/auth/v1/user`,{headers:{Authorization:auth,apikey:anonKey}});if(!ur.ok)return json(req,{error:"Tu sesión venció. Vuelve a iniciar sesión."},401);const user=await ur.json();const body=await req.json().catch(()=>({}));const profileId=Number(body.profileId);if(!Number.isInteger(profileId))return json(req,{error:"Primero guarda una tarjeta válida"},400);
 const h={Authorization:`Bearer ${serviceKey}`,apikey:serviceKey,"Content-Type":"application/json"};const pr=await fetch(`${supabaseUrl}/rest/v1/profiles?id=eq.${profileId}&user_id=eq.${user.id}&select=id,slug,name,data,subscription_plan,account_role,demo_profile`,{headers:h});const ps=await pr.json();if(!pr.ok||!ps?.[0])return json(req,{error:"Esta tarjeta no pertenece a tu cuenta"},403);const profile=ps[0];
 const sr=await fetch(`${supabaseUrl}/rest/v1/business_settings?id=eq.main&select=plan_prices,plan_promos,plan_promo_active`,{headers:h});const ss=await sr.json();if(!sr.ok)return json(req,{error:"No se pudo consultar el precio vigente"},503);const s=ss?.[0]??{};
 const allowed=["personal","business","artist","creator"];const requestedPlan=String(body.plan||"").toLowerCase();if(!allowed.includes(requestedPlan))return json(req,{error:"Selecciona un plan válido"},400);if(profile.account_role==="team"||profile.demo_profile===true)return json(req,{error:"Las tarjetas internas no generan cobros"},403);const plan=requestedPlan;
 const normal=Number(s.plan_prices?.[plan]),promo=Number(s.plan_promos?.[plan]),promoActive=s.plan_promo_active?.[plan]===true&&Number.isInteger(promo)&&promo>0&&promo<normal;const amount=promoActive?promo:normal;if(!Number.isInteger(amount)||amount<1||amount>999)return json(req,{error:"Precio del plan inválido"},500);
 const labels:{[k:string]:string}={personal:"Personal",business:"Business",artist:"Artista",creator:"Creator"};const attemptId=crypto.randomUUID(),externalReference=`clickonme-${profile.id}-${plan}-${attemptId}`;const preferenceResponse=await fetch("https://api.mercadopago.com/checkout/preferences",{method:"POST",headers:{Authorization:`Bearer ${mpToken}`,"Content-Type":"application/json","X-Idempotency-Key":attemptId},body:JSON.stringify({items:[{id:`clickonme-${plan}-anual`,title:`ClickOnMe ${labels[plan]} anual${promoActive?" · promoción":""}`,currency_id:"MXN",quantity:1,unit_price:amount}],payer:{email:String(user.email??"")},external_reference:externalReference,notification_url:`${supabaseUrl}/functions/v1/mercadopago-webhook?source_news=webhooks`,back_urls:{success:`https://clickonme.pro/crear/?id=${profile.id}&payment=success`,pending:`https://clickonme.pro/crear/?id=${profile.id}&payment=pending`,failure:`https://clickonme.pro/crear/?id=${profile.id}&payment=failure`},auto_return:"approved"})});const pref=await preferenceResponse.json().catch(()=>({}));const checkoutUrl=environment==="production"?pref.init_point:pref.sandbox_init_point;if(!preferenceResponse.ok||!pref.id||!checkoutUrl)return json(req,{error:"Mercado Pago rechazó la orden"},502);
 const save=await fetch(`${supabaseUrl}/rest/v1/payments`,{method:"POST",headers:{...h,Prefer:"return=minimal"},body:JSON.stringify({user_id:user.id,profile_id:profile.id,provider_order_id:String(pref.id),external_reference:externalReference,amount_mxn:amount,status:"created",environment,checkout_url:String(checkoutUrl),provider_payload:{api:"preferences",collector_id:pref.collector_id,plan,promo_active:promoActive,normal_price:normal}})});if(!save.ok)throw new Error(await save.text());return json(req,{checkoutUrl,orderId:String(pref.id),amount,environment,plan,offerLabel:labels[plan],promoActive,normalPrice:normal});
 }catch(e){console.error("Checkout error",e);return json(req,{error:"No se pudo preparar el pago"},500)}
});