begin;
create temp table catalog_results(test text,passed boolean) on commit drop;
create temp table catalog_fixture(admin_id uuid,owner_id uuid,pid bigint,sid uuid,seller_id uuid) on commit drop;
insert into catalog_fixture select user_id,gen_random_uuid(),null,gen_random_uuid(),null from public.admin_users limit 1;
insert into auth.users(id,email,email_confirmed_at,aud,role) select owner_id,'qa-catalog-'||owner_id||'@example.invalid',now(),'authenticated','authenticated' from catalog_fixture;
select set_config('request.jwt.claim.sub',(select admin_id::text from catalog_fixture),true);
do $$ declare f catalog_fixture;c public.profiles;s public.assisted_sales;r public.assisted_sales;v public.sales_representatives;u uuid;begin
 select * into f from catalog_fixture;
 select * into v from public.admin_save_sales_representative(null,'QA vendedor reversible','QA-'||substr(f.owner_id::text,1,8),true,20);
 update catalog_fixture set seller_id=v.id;
 insert into catalog_results values('seller_persistent_id_code_default_rate',v.id is not null and v.commission_percent=20 and v.active and v.created_at is not null);
 begin perform public.admin_save_sales_representative(null,'QA duplicado',v.code,true,20);insert into catalog_results values('duplicate_code_rejected',false);exception when unique_violation then insert into catalog_results values('duplicate_code_rejected',true);end;
 select * into c from public.admin_create_card('qa-catalog-'||substr(f.owner_id::text,1,8),'QA cliente catálogo');
 update public.profiles set description='QA edición de tarjeta antes de entrega' where id=c.id;
 perform public.admin_assign_profile_owner_server(f.admin_id,c.id,'qa-catalog-'||f.owner_id||'@example.invalid');
 update catalog_fixture set pid=c.id;
 select * into s from public.admin_record_catalog_sale(f.sid,c.id,'personal',500,v.id,'efectivo','QA-CATALOG-'||f.sid,now(),'Descuento QA');
 insert into catalog_results values('sale_links_seller_id',s.seller_id=v.id and s.seller_code=v.code and s.seller_name_snapshot=v.name);
 insert into catalog_results values('commission_20_percent_of_actual_payment',s.commission_percent=20 and s.commission_mxn=100 and s.commission_status='pending');
 insert into catalog_results select 'create_edit_deliver_activate_12_months',user_id=f.owner_id and description='QA edición de tarjeta antes de entrega' and status='active' and subscription_plan='personal' and current_period_end=now()+interval '12 months' from public.profiles where id=c.id;
 perform public.admin_mark_commission_paid(s.id,'QA-PAYOUT');
 perform public.admin_save_sales_representative(v.id,'QA nombre actualizado',v.code,false,25);
 select * into r from public.admin_record_catalog_sale(f.sid,c.id,'personal',500,v.id,'efectivo','QA-CATALOG-'||f.sid,now(),'Descuento QA');
 insert into catalog_results values('retry_preserves_paid_history_after_seller_changes',r.commission_status='paid' and r.commission_mxn=100 and r.commission_percent=20 and r.seller_name_snapshot=v.name and r.commission_reference='QA-PAYOUT');
 begin perform public.admin_record_catalog_sale(gen_random_uuid(),c.id,'personal',600,v.id,'efectivo','QA-INACTIVE-'||f.sid,now(),'');insert into catalog_results values('inactive_seller_rejected',false);exception when others then insert into catalog_results values('inactive_seller_rejected',sqlerrm like 'Selecciona un vendedor activo%');end;
 perform public.admin_save_sales_representative(v.id,v.name,v.code,true,20);
 select * into r from public.admin_record_catalog_sale(gen_random_uuid(),c.id,'personal',600,v.id,'efectivo','QA-RENEW-'||f.sid,now(),'');
 insert into catalog_results values('renewal_zero_percent_and_fee',r.commission_percent=0 and r.commission_mxn=0 and r.expires_at=s.expires_at+interval '12 months');
 u:=gen_random_uuid();insert into auth.users(id,email,email_confirmed_at,aud,role) values(u,'qa-direct-'||u||'@example.invalid',now(),'authenticated','authenticated');
 select * into c from public.admin_create_card('qa-direct-'||substr(u::text,1,8),'QA venta directa');
 perform public.admin_assign_profile_owner_server(f.admin_id,c.id,'qa-direct-'||u||'@example.invalid');
 select * into r from public.admin_record_catalog_sale(gen_random_uuid(),c.id,'creator',999,null,'efectivo','QA-DIRECT-'||u,now(),'');
 insert into catalog_results values('direct_sale_without_seller_zero_commission',r.seller_id is null and r.commission_percent=0 and r.commission_mxn=0 and r.commission_status='not_applicable');
 insert into catalog_results select 'direct_creator_12_months',current_period_end=now()+interval '12 months' and subscription_plan='creator' from public.profiles where id=c.id;
end $$;
grant all on catalog_results,catalog_fixture to authenticated;
set local role authenticated;
insert into catalog_results select 'admin_can_see_sale_and_seller',count(*)=1 from public.assisted_sales s join public.sales_representatives v on v.id=s.seller_id where s.id=(select sid from catalog_fixture);
select set_config('request.jwt.claim.sub',(select owner_id::text from catalog_fixture),true);
insert into catalog_results select 'customer_cannot_read_catalog',count(*)=0 from public.sales_representatives;
do $$ begin
 begin perform public.admin_save_sales_representative(null,'QA no autorizado','QA-DENIED',true,20);insert into catalog_results values('customer_cannot_manage_catalog',false);exception when insufficient_privilege then insert into catalog_results values('customer_cannot_manage_catalog',true);end;
 begin perform public.admin_record_catalog_sale(gen_random_uuid(),(select pid from catalog_fixture),'creator',999,null,'efectivo','QA-DENIED',now(),'');insert into catalog_results values('customer_cannot_record_sale',false);exception when insufficient_privilege then insert into catalog_results values('customer_cannot_record_sale',true);end;
end $$;
reset role;
insert into catalog_results values('anonymous_cannot_create_seller',not has_function_privilege('anon','public.admin_save_sales_representative(uuid,text,text,boolean,numeric)','EXECUTE'));
select * from catalog_results;
rollback;
